### ISSUE TITLE
Updates, comment

### ISSUE THREAD

**Issue by derpindaisy** [RayBB/random-stock-picker#1]
Hey Ray, thanks for this I really love using it to get ideas. Does the script that updates the list of stocks update every time the page is loaded?

Thanks again

**Comment by RayBB** [comment]
Hey there. The list of stocks is only updated when someone updates it in the repo.
I just updated it so it should have all the current stocks as of today.

**Comment by derpindaisy** [comment]
Thanks, is there anyway for me to update it?

**Comment by RayBB** [comment]
Yes, if you rush the bash script that's included and then open the HTML file on your computer.
