### ISSUE TITLE
Licence? Fork?

### ISSUE THREAD

**Issue by aflugge** [RayBB/random-stock-picker#3]
I am thinking of building my own random stock picker. I like your design so would like to use your page as a start for my project if that is ok with you. I am planning to restrict my stock picker to stocks that can be traded by the UK investment platform orca.app and add some options to limit to ethical investment options (black list some companies/sectors). Would also add my own referal link for orca.app. 

Is your code under some form of open source licence? Or are you ok, with me re-using it as described above?

**Comment by aflugge** [comment]
I have now forked it, please let me know, if you don't want me to use it in such a way. https://github.com/aflugge/orca-random-stock-picker

**Comment by RayBB** [comment]
@aflugge I appreciate you asking and I think it's awesome that you're using it for that investment platform!

I went ahead and added you to a list of forks and added a license 👍
